### ISSUE TITLE
Perl Segmentation fault: 11

### ISSUE THREAD

**Issue by bretonics** [ViennaRNA/ViennaRNA#1]
There is a `segmentation fault: 11` when calling in perl
> RNA::PS_dot_plot($sequence, "dot.ps");       # write dot plot to dot.ps

**Comment by RaumZeit** [comment]
Can you please provide a minimal non-working example?
Maybe you've not met all pre-conditions for a call to PS_dot_plot()?

**Comment by bretonics** [comment]
I pass 2 variables, `$name` and `$sequence` (`CRISPR` and `ATGCTGATCGTATTAGCCTGACGG`) to a module subroutine. The subroutine is as followed:

```perl
my ($name, $sequence) = @_;
my $outFile = "ss/$name";

my ($ss, $mfe) = RNA::fold($sequence);
my $F = RNA::pf_fold($sequence); # compute partition function and pair pobabilities
RNA::PS_rna_plot($sequence, $ss, "$outFile\_rna.ps"); # write PS plot to CRISPR_#_rna.ps
RNA::PS_dot_plot($sequence, "$outFile\_dot.ps"); # write dot plot to dot.ps
return;
```
It writes the *_rna.ps file, but not the *dot.ps.

**Comment by RaumZeit** [comment]
That's odd. Which version of the RNA module are you using? I just tried to reproduce the segfault using ViennaRNA Package 2.3.0 using your snippet::
```perl
use RNA;

my ($name, $sequence) = ("CRISPR", "ATGCTGATCGTATTAGCCTGACGG");
my $outFile = "ss/$name";

print "Version: ", RNA::VERSION, "\n";

my ($ss, $mfe) = RNA::fold($sequence);
my $F = RNA::pf_fold($sequence); # compute partition function and pair pobabilities
RNA::PS_rna_plot($sequence, $ss, "$outFile\_rna.ps"); # write PS plot to CRISPR_#_rna.ps
RNA::PS_dot_plot($sequence, "$outFile\_dot.ps"); # write dot plot to dot.ps
```
Instead of segfaulting, I get two warnings
```
2.3.0
WARNING: can't open file ss/CRISPR_rna.ps - not doing xy_plot
WARNING: can't open ss/CRISPR_dot.ps for dot plot
```
that the output files can't be opened for writing, which is due to the fact that the 'ss/' subdirectory doesn't exist. If I create the subdir first, everything works fine.

**Comment by bretonics** [comment]
I must have had this line commented out every time I tried it before...
> my $F = RNA::pf_fold($sequence); # compute partition function and pair probabilities

I just tried it again and worked uncommented. 

Why is this necessary if I am not using the returned variable from `RNA::pf_fold($sequence);` in the `RNA::PS_dot_plot($sequence, "$outFile\_dot.ps"` call?

**Comment by RaumZeit** [comment]
Good to hear that it's working for you now!
The reason, however, why you have to call the `pf_fold()` function is (in parts) due to historical reasons. `pf_fold()` will fill the partition function matrices and compute the  base pair probabilities. But the function only returns the ensemble free energy and stores the pairing propensity for each nucleotide in a pseudo dot-bracket string provided as the second argument. The pairing probabilties themselves are stored in a global variable. This global variable is then accessed by the plotting function to actually create the dot-plot. 
_This is the 'old' way to deal with our RNA library, which is not threadsafe and therefore discouraged (see also the reference manual for that function)._

A (newer and) better variant of the EPS dot-plot function requires one to pass a list of base pair probabilities instead, thereby rendering the global variable obsolete. In one of the next releases, the dot-plot function will be added as a method to the new object-oriented scripting language interface.

**Comment by bretonics** [comment]
Awesome, thank you for the explanation!

It makes sense now why it wasn't working because I never added that call until right before I gave up for the day, putting it there to come back to in the morning since I saw it in the doc example. Never thought it made a difference, but the global variable makes sense.

I've also have the situation that the images with the `relplot.pl` are not rendered fully inside the image canvas. Shall I open a new issue and detail further? I emailed last week, but never got a response.

Thanks again.
