### ISSUE TITLE
error during make, yacc

### ISSUE THREAD

**Issue by Cdk29** [ViennaRNA/ViennaRNA#10]
Hi.

During a make from the last version of ViennaRNA, cloned from the git repository, I get the following error : 

make[4]: Leaving directory '/users/(...)/src/RNAforester/g2-0.72'
Making all in src
make[4]: Entering directory '/users/(...)/src/ViennaRNA/src/RNAforester/src'
  YACC     anchors/shape.cpp
yacc: e - line 12 of "/users/(...)/ViennaRNA/src/RNAforester/src/anchors/shape.ypp", syntax error
%debug    /* yacc -t */ /* FIXME */
^
Makefile:583: recipe for target 'anchors/shape.cpp' failed
make[4]: *** [anchors/shape.cpp] Error 1

I have tried to install various package with yacc inside, including bison, byacc, freebsd-glue, golang-go, cook, 9base, but nothing work.
I am on debian.

**Comment by RaumZeit** [comment]
The error message you've encountered is actually due to some strange behavior of bison being split into multiple packages. On debian or red-hat like systems, many libraries are split into a development package, and the actual binary library/program package. Unfortunately, some programs however require files from their respective development package to work correctly. This is also the case for `bison`. If you are on Debian/Ubuntu, please also install the `libbison-dev` package. This should solve the compilation error.
