### ISSUE TITLE
Questions on RNAplfold

### ISSUE THREAD

**Issue by ruthkr** [ViennaRNA/ViennaRNA#100]
Dear ViennaRNA team, 

Thank you very much for the great tool. 
I am a beginner in this RNA folding world, and I am learning how to use ViennaRNA. 

My goal: to get a folding prediction using sliding windows of the whole genome of Beet Mild Yellowing Virus. 

I am planning to use ViennaRNA binary: `RNAplfold` that already implement sliding windows. 

My questions:
1. As I understand about the sliding windows concept, I need to define window size and step size. However, I could not find a step size as a parameter in `RNAplfold`. How do you implement sliding windows in `RNAplfold` or in ViennaRNA in general? 

2. After I perform `RNAplfold`, how can I get the positional MFE and positional entropy? I tried to replicate the code on getting the entropy from mountain.pl and relplot.pl, but I could not really get the same result. 

Thank you very much for your time. I am looking forward to hearing from you as I will greatly help my research and my understanding.

**Comment by RaumZeit** [comment]
Dear ruthkr,

in `RNAplfold` the stepsize for the sliding windows is always 1. The two parameters that are user-adjustable are the window size (`w`), and the maximum base pair span (`L`). Calling the `RNAplfold` program then automatically moves a window from 5' to 3' ends of the input sequence to compute average pairing probabilities for all nucleotides from their respective probabilities in all windows they overlap with.

For your second question, you might want to use the program `RNALfold` instead. This will predict locally stable secondary structure components for each window. You can then further analyze the components or with the latest version, construct a global structure with limited base pair span using the `-b` option. Positional entropies can, so far, NOT be automatically computed from the output of `RNAplfold` using the `mountain.pl` or `relplot.pl` scripts. This is mainly due to the case that these scripts assume that pairing proabilities with the same pairing partner are within range [0,1], but in `RNAplfold` the probabilites are in [0,2] due to the averaging over all windows. One should always keep that in mind. Of course, you can still go ahead to implement your own positional entropy computation from the output of `RNAplfold`.
