### ISSUE TITLE
ERROR: backtracking failed in fML

### ISSUE THREAD

**Issue by VandaLovejoy** [ViennaRNA/ViennaRNA#113]
Hello! I got a backtracking error when trying to run RNALalifold on a multiple alignment format. 
`13 sequences; length of alignment 139407.
.((((....)))). ( -1.77) 139347 - 139360
ERROR: backtracking failed in fML, segment [139323,139336]
`

[test2.maf.txt](https://github.com/ViennaRNA/ViennaRNA/files/6306485/test2.maf.txt)

**Comment by RaumZeit** [comment]
Hi,
thanks for pointing out this bug! I've already located the problem and applied a fix. Apparently, backtracing in `RNALalifold` was broken since v2.4.17 due to a missing initialization of the dynamic programming matrices. You might want to consider using v2.4.16 or earlier, or just wait a few days until v2.4.18 will be released that, among other things, actually fixes this bug.

I'm very sorry for the inconvenience!

**Comment by VandaLovejoy** [comment]
Thanks for your response Ronny! I'll use the 2.4.16 version instead!

**Comment by RaumZeit** [comment]
Fixed with version 2.4.18
