### ISSUE TITLE
Installation issue for MacOs

### ISSUE THREAD

**Issue by CindyWXQ** [ViennaRNA/ViennaRNA#114]
I installed precompiled Binary Package for MacOs X, it says

```
ImportError: dlopen(/usr/local/lib/python2.7/site-packages/RNA/_RNA.so, 2): Library not loaded: /usr/local/opt/mpfr/lib/libmpfr.4.dylib
  Referenced from: /usr/local/lib/python2.7/site-packages/RNA/_RNA.so
  Reason: image not found
```

**Comment by RaumZeit** [comment]
Hi,
unfortunately, our pre-build Mac binaries are linked against an older version of `libmpfr` from `homebrew`. If you have installed a more recent (or even older) version of `mpfr`, you might want to consider the fix proposed here: https://github.com/ViennaRNA/ViennaRNA/issues/98

Otherwise, I'm afraid you need to compile the ViennaRNA Package from source or wait for the next release. With the upcoming version 2.4.18 I'll try to maintain two binary installer packages for Mac OS X, one that links against recent libraries available with `homebrew` and a second that only links to Mac OS X core libraries.

**Comment by RaumZeit** [comment]
With the new release of ViennaRNA Package 2.4.18 today, two installers are available as mentioned above.
Also, I added a description on the required extra packages from homebrew, if users are installing the binaries linked against mpfr, perl5, and python 3.9 from homebrew.

I consider this issue closed now. Feel free to re-open if the problem persists.
