### ISSUE TITLE
wrong energy parameter?

### ISSUE THREAD

**Issue by sjanssen2** [ViennaRNA/ViennaRNA#115]
dangling A onto a CG base-pair is DEF? This looks wrong for old Turner 1999 parameters. I think it should be -50: http://rna.urmc.rochester.edu/NNDB/turner99/dangle.txt 
https://github.com/ViennaRNA/ViennaRNA/blob/5d0cf4fb5e794a9859c893fad2a7f34ac64cc403/misc/rna_turner1999.par#L473

**Comment by RaumZeit** [comment]
But `DEF` is already -50:

https://github.com/ViennaRNA/ViennaRNA/blob/5d0cf4fb5e794a9859c893fad2a7f34ac64cc403/src/ViennaRNA/params/default.c#L54

... or do I misinterpret your question?

**Comment by sjanssen2** [comment]
oh, I didn't see this definition. If you only look at the file, this is a bit confusing. Also, the `DEF` does not occur in `rna_turner2004.par` although the same value is set to `-50`. This seems to be inconsistent - at least to me.

**Comment by RaumZeit** [comment]
The energy parameter files have been produced by different parsers/converters, that's why some contain the `DEF` placeholder while others don't. But since I also find it inconsistent and actually dislike the placeholder, I just replaced all the occurences of `DEF` in our parameter files with their actual value -50.

This change will be visible in the next release of the ViennaRNA Package.

**Comment by sjanssen2** [comment]
:+1:

**Comment by RaumZeit** [comment]
Fixed with https://github.com/ViennaRNA/ViennaRNA/commit/405bdb8dab91342510dd6db36fe6711b6a447b07 in Version 2.4.18

I'm closing this issue now. Feel free to reopen if required ;)
