### ISSUE TITLE
RNAalifold aln.ps case sensitivity

### ISSUE THREAD

**Issue by mmiladi** [ViennaRNA/ViennaRNA#12]
Hello Vienna,

An  issue with RNAalifold colored output alignment `aln.ps`: The visualization is case sensitive for coloring incompatible base-pairs and calculating conservation. Error depends on input format and at least with stockholm input this is the case. Invoked command `RNAalifold -f S --color --aln < test.stk`
![aln1](https://user-images.githubusercontent.com/6370737/30254151-906364c0-9694-11e7-82e6-417a4f4eebe6.png)
![aln2](https://user-images.githubusercontent.com/6370737/30254152-90637c12-9694-11e7-9f04-ec6ce60d0fd9.png)

Greetings,
Milad

**Comment by RaumZeit** [comment]
This is odd, maybe you are using an older version of RNAalifold?
We already addressed this issue for input sequences read from STOCKHOLM files by converting them to uppercase letters since version 2.4.0 (see https://github.com/ViennaRNA/ViennaRNA/commit/f5c9427bff884e882615e545e1670ad507e2c194#diff-83e1ec169a0432924c35216a3ca19347R608)

This behavior is still not really satisfying for me since one looses upper/lower case sequence annotation in the output files. In one of the next releases, I'll certainly change this behavior to something similar to what we are doing in RNAfold and other single sequence structure prediction programs. For them, we simply store the original input sequence, and use an uppercase converted copy for computations that require uppercase-only. Upon sequence output, the original sequence is used again...

**Comment by mmiladi** [comment]
Well true, I am using latest version from Conda which is 2.3.5. This answers my question and resolves the issue.

Maybe I can (ab)use this channel and ask/request some feature. Is there a way to colorize alignment & secondary structure plots with column conservation information instead of covariation? For example Rfam provides it but I am not sure if they vrna or some other tools.

**Comment by RaumZeit** [comment]
I'll put that on the feature-request list :)
- Additional annotation of alignment columns/consensus structure using sequence and base pair conservation

**Comment by mmiladi** [comment]
Danke schön! :)
