### ISSUE TITLE
Convert RNAplfold output to RNAfold style dot-bracket notation?

### ISSUE THREAD

**Issue by michauhl** [ViennaRNA/ViennaRNA#120]
Hi, 
I wonder if it is possible to convert the base pair output of RNAplfold to RNAfold style dot-bracket notation using ViennaRNA ? I assume that one has to first filter by base pair probabilities (>= 0.5 ?), to get unique base pairs needed for the dot-bracket notation ? But maybe it's not possible due to the sliding window approach, not sure.

Any help would be greatly appreciated!

Thanks & Best regards,
Michael

**Comment by RaumZeit** [comment]
Hi Michael,

in principle, this is possible. We already presented a way to compute the Maximum Expected Accuracy (MEA) structure from sliding-window base pair probability output (see https://www.mdpi.com/2073-4425/12/1/14), but the implementation is still lacking.

Simply taking all pairs (i,j) with  p_ij > 0.5 may not work (or at least misleading) for RNAplfold output, since pairing probabilities are always averages over all windows the base pair may be present in. I'll think about that one more time and get back to you.

Best,
Ronny

**Comment by michauhl** [comment]
Hi Ronny,

thank you for the info! Sorry for the late reply, totally forgot that I posted this :see_no_evil:

So this feature could be available at some point inside RNALfold ?

Best,
Michael
