### ISSUE TITLE
Explanation of `Law_and_Order` variable

### ISSUE THREAD

**Issue by vivkr** [ViennaRNA/ViennaRNA#121]
`src/ViennaRNA/pair_mat.h` defines a variable `Law_and_Order` (`static const char Law_and_Order[]         = "_ACGUTXKI"`) which has no documentation, but is used by `vrna_nucleotide_encode` to encode a nucleotide. Is there any particular reason this variable in named `Law_and_Order` (in relation to the syn bio domain)?

Also, why are the letters X, K, I included in the encoding process as they don't appear in DNA/RNA sequences?

(I'm just a newbie so likely have a terrible understanding of the field)

**Comment by RaumZeit** [comment]
This variable simply helps us to encode from characters to integer representations that we use internally. That's why this variable is called law and order. 
The characters you see here are all currently supported and distinguished nucleotides. Note, however, that X K and I are more remnants of past for some special purposes and may not work as expected. Especially, since there are no corresponding energy parameters available.
