### ISSUE TITLE
Potential bug: Incorrect setting of 5-prime mismatch in `energy_of_ml_pt`

### ISSUE THREAD

**Issue by v-raja** [ViennaRNA/ViennaRNA#126]
In `energy_of_ml_pt`, `i` is the nucleotide at the 5-prime end and `j` is the nucleotide at the 3-prime end of the closing base pair of the multi-loop. 

When setting the mismatching nucleotide at the 5-prime end, however, we use `j` (the nucleotide at the 3-prime end) to set it:
https://github.com/ViennaRNA/ViennaRNA/blob/d6fbaf2b33d65944f9249a91ed5ab4b3277f7d06/src/ViennaRNA/eval.c#L1604

Is this a bug, or is this deliberate? 

If it is deliberate, could anyone explain why the nucleotide at the 3-prime end is used to set the 5-prime mismatch? This seems to be inconsistent with how the 5-prime mismatch `mm5` is set throughout the ViennaRNA code base.

**Comment by RaumZeit** [comment]
Hi,
this is **not** a bug, but due to the directionality of the RNA strand (5' -> 3').
Actually, this also refers to your previous question, why G-C pairs are encoded differently to C-G pairs. Please have a look at how free energies are assessed in the RNA secondary structure Nearest Neighbor energy model, e.g.: https://rna.urmc.rochester.edu/NNDB/turner04/index.html.

**Comment by v-raja** [comment]
Thank you for the information @RaumZeit, it was very useful. I also got some clarity after reading through the `man/RNAlib.texi` file.
