### ISSUE TITLE
Does it possible to find hairpin loops with RNAfold for 7 and 8 nucleotide sequences?

### ISSUE THREAD

**Issue by DmitriiSukhomlinov** [ViennaRNA/ViennaRNA#132]
RNAfold can find a simple hairpin if it at least is 9 nucleoside long - 3 nucleotide for the 5' end helix part, 3 nucleotide for the loop and 3 nucleotide for the 3' end helix part. For example:

```
5'    GCGGACCGC   3'
      (((...)))
```
If we draw the picture, it looks like this:
![image](https://user-images.githubusercontent.com/26257527/125625199-60e24121-20ed-4788-8bd6-2dac3ffd8149.png)

The loop par of sequence really should be at least 3 nucleotide long - it's impossible to be shorter for this part of the sequence. But, actually, it's possible to make the helix just 2 nucleotide from each side. By the way, [this service](https://www.idtdna.com/calc/analyzer)  can do it and can find hairpins like this:

```
5'    GCGGACCG   3'
      .((...))
```

Or how it looks like in the picture:

![image](https://user-images.githubusercontent.com/26257527/125626358-6320e2e9-7386-4107-8898-133eaeb2d8b7.png)

So, the question is -  does it possible to find hairpins like this with RNAfold? For now, RNAfold don't find anything. If not - maybe you can fix it in the nearest future? Or just point me the place in the code where this is processed so I can fix it by my own?

Thanks!

**Comment by RaumZeit** [comment]
If you already know the structure and the sequence, you could use `RNAeval` to simply evaluate the sequence/structure pair and obtain the corresponding free energy.
Otherwise, `RNAfold` will always compute the MFE structure by default, that is the structure with minimal free energy. For such short sequences, however, the free energy of a hairpin that is just closed by a simple stack of two base pairs, the total free energy might be positive. Hence, the MFE structure is the unfolded state (or open chain), without any base pairs, since by definition, its free energy is 0.

**Comment by s-will** [comment]
As a quick additional remark: Such structures would be found as suboptimal structures by the tool RNAsubopt. For example,
```
$ RNAsubopt -e3 <<<GCGGACCGC
GCGGACCGC  -0.40   3.00
((.....))   0.80
(((...)))  -0.40
.((...)).   1.90
.........   0.00
```
Note that in your example the hairpins with only 2 base pairs are much less stable (as @RaumZeit  wrote above, they have positive energy), therefore we see them even with RNAsubopt only after setting relatively high energy tolerances (here set by ```-e3```).
