### ISSUE TITLE
Error while compiling ViennaRNA

### ISSUE THREAD

**Issue by tongtong1993** [ViennaRNA/ViennaRNA#133]
I've followed the installation instruction in README as follow:

```
tar -zxvf ViennaRNA-2.4.18.tar.gz
cd ViennaRNA-2.4.18
./configure --prefix=/home/username/ViennaRNA
make install
```
However I got an error like this.
```
make[2]: Entering directory `/home/tongtong1993/Tools/ViennaRNA-2.4.18/interfaces/Perl'
  CXX      RNA_la-RNA_wrap.lo
RNA_wrap.cpp:763:20: fatal error: EXTERN.h: No such file or directory
 #include "EXTERN.h"
                    ^
compilation terminated.
make[2]: *** [RNA_la-RNA_wrap.lo] Error 1
make[2]: Leaving directory `/home/tongtong1993/Tools/ViennaRNA-2.4.18/interfaces/Perl'
make[1]: *** [install-recursive] Error 1
make[1]: Leaving directory `/home/tongtong1993/Tools/ViennaRNA-2.4.18/interfaces'
make: *** [install-recursive] Error 1

```
How can I fix this? Thank you very much.

**Comment by raven44099** [comment]
I encountered a similar error message when I followed almost the same instructions. Instead of `make install` is used `make`.

Here is the error I received:
```
In file included from RNA_wrap.cpp:764:
/home/ubuntuds64/miniconda3/lib/5.32.0/x86_64-linux-thread-multi/CORE/perl.h:861:13: fatal error: xlocale.h: No such file or directory
  861 | #   include <xlocale.h>
      |             ^~~~~~~~~~~
compilation terminated.
make[3]: *** [Makefile:717: RNA_la-RNA_wrap.lo] Error 1
make[3]: Leaving directory '/home/ubuntuds64/Tutorial/downloads/ViennaRNA-2.4.18/interfaces/Perl'
make[2]: *** [Makefile:620: all-recursive] Error 1
make[2]: Leaving directory '/home/ubuntuds64/Tutorial/downloads/ViennaRNA-2.4.18/interfaces'
make[1]: *** [Makefile:678: all-recursive] Error 1
make[1]: Leaving directory '/home/ubuntuds64/Tutorial/downloads/ViennaRNA-2.4.18'
make: *** [Makefile:569: all] Error 2
```
Configuration said I can now execute `make`, `make check `and `make install`.

Please, If someone can help me resolve this I would be very thankful :) I dont understand this message. Is it that I miss perl (I'm a python user only)?

**Comment by raven44099** [comment]
Since I am frequently using miniconda and I am not sure wether I installed perl in that environment, I tried miniconda to install ViennaRNA. Running $ RNAfold < test.seq
gave me the expected output:
CUACGGCGCGGCGCCCUUGGCGA
...........((((...)))). ( -5.00) 

You might have the same problem as I.

**Comment by RaumZeit** [comment]
From the compile error messages I see, I assume that you are trying to compile on a Mac? If so, one has to set some more environment variables to point to the correct Perl 5 environment. The problem here is, that the Perl 5 interpreter that comes with Mac OS X is not intended for use with other software than that of Apple. Users are advised to install a more recent Perl 5 from homebrew or such else. Done that, the correct headers should be installed and put into the respective environment variables.
(See also https://stackoverflow.com/questions/52682304/fatal-error-extern-h-file-not-found-while-installing-perl-modules/52997962 and other conversations about the missing `EXTERN.h` file)

On the other hand, if you are using a Linux distriibution and encounter this error, please make sure to have installed the `perl-dev` or `perl-devel` packages. These should install the missing header files as well.

Lastly, if you do not intend to use the Perl 5 interface, you could also just disable it at configure time using the `--without-perl` switch in addition to your other `./configure` parameters. This will disable the build of the Perl 5 interface in the subsequent `make` process.

I hope this is of help. Let me know if these solutions work for you.
