### ISSUE TITLE
error compiling with gcc 4.8.5

### ISSUE THREAD

**Issue by aspitaleri** [ViennaRNA/ViennaRNA#146]
Hi there,
ViennaRNA 2.5 compiling was dying here:

../dlib-19.22/dlib/all/libRNA_concentrations_la-source.lo
with no error at all.
Update to gcc version > 7 everything went smoothly.

My configure is
./configure --prefix=/SOFTW/ViennaRNA-2.5 --with-kinwalker --with-cluster --with-python3 --without-cla-pdf --without-cla

**Comment by B199944-2021** [comment]
In my case, some error message would pop out. The dlib 19.22 has dropped support for GCC 4.85 and older, which was the default compiler for centos 7 and some other Linux systems. I think they'd better update this issue on the install page next time.

**Comment by RaumZeit** [comment]
That is unfortunate! We added `dlib` to our source tree for version 2.5.0 to efficiently compute concentration dependencies upon multi-strand interactions. Apparently, `dlib` requires a more recent compiler that actually implements the C++17 standard, which is only available since GCC 5.
I'll see whether I can put a more prominent note in the build requirements section.
