### ISSUE TITLE
Base pairing criteria in RNAalifold

### ISSUE THREAD

**Issue by Abhinav-Mittal** [ViennaRNA/ViennaRNA#168]
How do I set up cutoff for base pairing between i,j positions of alignment in RNAalifold? It is mentioned in https://bmcbioinformatics.biomedcentral.com/articles/10.1186/1471-2105-9-474 

![image](https://user-images.githubusercontent.com/6822184/200299198-8fe5ea58-95f0-4a09-8a8f-a387336239cb.png)

**Comment by RaumZeit** [comment]
This can be done using the `--nfactor` and `--cfactor` command line parameters. Using a `--nfactor` between 0 and 1 results in higher numbers of possible pairs between alignment columns, since counter-examples, i.e. sequences that can pair given the two alignment columns receive a lower penalty the lower the `--nfactor` is.

**Comment by RaumZeit** [comment]
No further updates on this issue, so I assume it is fixed.
I therefore close this issue now, please feel free to re-open if any questions remain.
