### ISSUE TITLE
RNA:DNA hybrid duplex energy parameters

### ISSUE THREAD

**Issue by SreeniEadara** [ViennaRNA/ViennaRNA#202]
Hi,
In this paper (https://pubmed.ncbi.nlm.nih.gov/22829626/) you discuss a nice technique for folding of RNA:DNA hybrid duplexes of 2 strands using previously published energy data.
I notice that a previous version supported folding of these duplexes (https://github.com/ViennaRNA/ViennaRNA/issues/135).

Is there an energy params file that we can load in 2.6.3 to fold RNA:DNA hybrid duplexes? I'm looking at this specifically:
https://www.tbi.univie.ac.at/RNA/ViennaRNA/doc/html/eval/params/io.html

**Comment by RaumZeit** [comment]
Unfortunately, RNA/DNA hybrid support never found its way into the official release. The only working solution at this moment is to use v2.1.9h. Here, the programs `RNAcofold`, `RNAup`, and `RNAduplex` have been rewritten to always assume that the first input sequence is RNA and the second is DNA. But as you might guess already, the API of v2.1.9h is not as developed as our current release and all of the features we implemented since then are not available for the RNA/DNA hybrid release.

We will be working on an integration of the RNA/DNA hybrid support again some time in the future as it is very much related to our latest additions of modified RNA bases. However, I can't tell when exactly this will happen.
