### ISSUE TITLE
RNA.cofold cut_point in Python3

### ISSUE THREAD

**Issue by ihwang** [ViennaRNA/ViennaRNA#21]
(I emailed this question to rna@tbi.univie.ac.at yesterday but figured that this might be a more appropriate venue for such a question; apologies if inappropriate).

I'd like to integrate folding results with other code in Python, but am having trouble using RNA.cofold. I have found a great example for using RNAfold (fold_compound) in python [here](https://www.tbi.univie.ac.at/RNA/ViennaRNA/doc/html/mp_example.html#scripting_python_examples_oo), but it does not address how to set [cut_point](https://www.tbi.univie.ac.at/RNA/ViennaRNA/doc/html/group__mfe__cofold.html#gabc8517f22cfe70595ee81fc837910d52) for the RNA.cofold method. I have tried setting cut_point earlier in my code, but that appears to have no effect, and when I try setting a cut point with an ampersand ('&') in my sequence, the ampersand appears to be treated as just another sequence base. What is the correct way to set cut points when using RNA.cofold in Python3?

**Comment by RaumZeit** [comment]
Dear Irena,
sorry for the confusing examples. In fact, there are two ways to approach your task:
1. 'Old' (simple) API:
```
import RNA
RNA.cvar.cut_point=51
RNA.cofold("UGGGAAUAGUCUCUUCCGAGUCUCGCGGGCGACGGGCGAUCUUCGAAAGUUGGGAAUAGUCUCUUCCGAGUCUCGCGGGCGACGGGCGAUCUUCGAAAGUGGAAUCCGUACUUAUACCGCCUGUGCGGACUACUAUCCUGACCACAUAGU")
```
Note, that the global cut_point variable (as all other global variables) in python is located in RNA.cvar
Using this interface requires one to _omit_ the ampersand indicating teh split in the sequence. Otherwise it will be treated as an additional nucleotide that just can't pair.

2. 'New' object oriented API:
```
import RNA
fc = RNA.fold_compound("UGGGAAUAGUCUCUUCCGAGUCUCGCGGGCGACGGGCGAUCUUCGAAAGU&UGGGAAUAGUCUCUUCCGAGUCUCGCGGGCGACGGGCGAUCUUCGAAAGUGGAAUCCGUACUUAUACCGCCUGUGCGGACUACUAUCCUGACCACAUAGU")
fc.mfe_dimer()
```
Unfortunately, the `mfe()` method is not overloaded yet, so one has to explicitly call the `mfe_dimer()` method to compute the MFE structure upon hybridization of the two molecules. Note, using the `fold_compound`, one has to _include_ the ampersand separating the two strands in the input sequence. It will be automatically sliced out when the `fold_compound` object is created, hence not appearing in any of the outputs.

I hope this helps!
Best,
Ronny

**Comment by ihwang** [comment]
Perfect, thanks very much! Another question: is there a way to add hard constraints to the structure, usually indicated with the −C flag in the command line interface?

**Comment by martin-mann** [comment]
@ihwang the actual question is: What do you want to compute?

short answer: you cannot constrain the way you want it! cofold will always provide you with both intra- and intermolecular base pairs, since it optimizes both at the same time.. that your example produces no intramolecular base pairs for the first sequence is just random (and maybe due to the shortness of the sequence).

if you are interested *only* in the intermolecular base pairs, you can
- identify and remove all intramolecular base pairs from the cofold result (remove any base pair closed before the `&` or opened after it)
- switch to a different prediction model: 
   - either hybrid-only predictions (e.g. RNAhybrid tool), which will overestimate your interaction or
   - an accessibility-based model (e.g. RNAup or IntaRNA), which will only report the interacting base pairs with a more sophisticated prediction model compared to cofolding. for [IntaRNA](/BackofenLab/IntaRNA), there is no python API so far, but a system call producing parsable CSV can be easily generated.

hope that helps,
Martin
