### ISSUE TITLE
[Bug]: RNA.duplexfold energy not affected by cvar.salt

### ISSUE THREAD

**Issue by mtod92** [ViennaRNA/ViennaRNA#226]
### Contact Details

todisco@wi.mit.edu

### What happened?

Hello,

I am trying to use duplexfold API in Python to calculate the MFE for hybridization of two strands neglecting their intramolecular interactions.
I can see that the output changes as I change the globally set temperature (RNA.cvar.temperature) but it seems to be insensitive to salt concentration (RNA.cvar.salt).
Am I doing something wrong? Is this feature not supported yet?
Here is my code snippet:
import RNA
RNA.cvar.temperature = 37
RNA.cvar.salt = 1000

seq1 = 'AACGGACUU'
seq2 = 'AACUCCGUU'

fc  = RNA.duplexfold(seq_A, seq_B)
print(fc.energy)

Thanks a lot!
Marco

### Version

2.6.x (Default)

### Which operating system are you using?

Mac OS X

### Does the problem occur with one of our executable program or the C-library?

Python 3 interface

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by RaumZeit** [comment]
Hi,

in principle, salt concentration changes should be applicable with the RNAduplex algorithm. They are implemented in the `RNAduplex` program, and internally handled in the library. However, after checking you example code, I also found that changes in salt concentration do not change the outcome of the prediction. In particular, the following behavior is found:

Once `RNA.duplexfold()` is called with any pre-set `RNA.cvar.salt` value, any future changes of the salt concentration with subsequent `RNA.duplexfold()` executions will lead to the same result. I also identified the reason behind this buggy behavior: `RNA.duplexfold()` still uses the old v1.8.x API. Internally, the energy parameters are pre-computed once and then re-used for each subsequent call. The implementation checks whether any important model settings have changed since the last call, e.g. `RNA.cvar.temperature`, and updates the parameters if necessary. However, these checks do not include changes in salt concentration!

So, for now, to circumvent this bug, together with changing the salt concentration, you may consider changing the temperature to any arbitrary value (different to the settings before). Then, execute `RNA.duplexfold()` once and omit the result for the 'wrong' temperature. Now, change the temperature back to the original settings, and run `RNA.duplexfold()` again. This time, the internal energy parameters reflect those with your desired salt concentration and temperature settings...

I'll see that a fix for that will become available in the next release.

Let me know if the problem persists for you or if you need any further assistance!

Cheers,
Ronny

**Comment by mtod92** [comment]
Thanks a lot!
