### ISSUE TITLE
Base-pair probabilities off?

### ISSUE THREAD

**Issue by sjanssen2** [ViennaRNA/ViennaRNA#242]
Hi,

I wonder why there are discrepancies in computation of base-pair probabilities between `RNAfold -p` and `RNAsubopt`.

The RNA sequence `CACUGUAAAGCUAACUUAGCAUUAACCUUGACUUU` can fold into 2,288 structures when disallowing lonely base-pairs (double check via http://bellmanscafe.jlab.bio/ `gra_overdangle(alg_count, CACUGUAAAGCUAACUUAGCAUUAACCUUGACUUU)`).

When we enumerate all these folds and compute their energy via `echo CACUGUAAAGCUAACUUAGCAUUAACCUUGACUUU | RNAsubopt --noLP -e 100000 -d2 > subopt_overdangle.txt` we indeed retrieve 2,288 answers. Here are the first 10 lines:
```
CACUGUAAAGCUAACUUAGCAUUAACCUUGACUUU  -1.40 100000.00
......((.........................))   6.60
......((((.....)).....((....))...))  16.70
......((((....))......((....))...))  14.20
......((...((...))....((....))...))  16.40
......((..((.....))...((....))...))  14.60
......((..(((...)))...((....))...))  13.80
......((.((.......))..((....))...))  12.90
......((.(((.....)))..((....))...))  11.20
......((.((((...))))..((....))...))  10.40
```
If we take the tedious, manual route, we can compute base pair probabilities from this result, by
  1. converting free energies via `exp((-1 * energy ) / (1.98717 / 1000 * (37 + 273.15)))` where 1.98717 is the gas constant, 37 room temperature, 273.15 = 0°K.
  2. summing up converted energy values for all folds that have a specific base pair, e.g. at bases 5 and 26, which form a `G-C` pair. You can pick folds having this base-pair with `grep` via `cat subopt_overdangle.txt | grep "^....(....................)........."`, there are the following 74:

```
((..((..................))..)).....   3.10
((..((..((....))((....))))..)).....   8.10
((..((..........((....))))..)).....   6.20
((..((......((.......)).))..)).....   8.00
((..((.....((...))......))..)).....   5.70
((..((.....((.........))))..)).....   6.10
((..((.....(((.......)))))..)).....   5.20
((..((....((.....)).....))..)).....   3.50
((..((....(((...))).....))..)).....   2.70
((..((...((.......))....))..)).....   1.50
((..((...(((.....)))....))..)).....  -0.20
((..((...((((...))))....))..)).....  -1.00
((..((..((....))........))..)).....   5.80
((..((..((.....)).......))..)).....   8.20
((..((..((...........)).))..)).....   6.10
((..((..((.((...))...)).))..)).....   7.90
((..((..((((.....))..)).))..)).....   6.20
((..((..(((((...)))..)).))..)).....   5.40
((..((.((......)).......))..)).....   7.20
((..((.(((....))).......))..)).....   4.70
((..((.((............)).))..)).....   3.00
((..((.((..((...))...)).))..)).....   5.00
((..((.((.((.....))..)).))..)).....   2.70
((..((.((.(((...)))..)).))..)).....   1.90
((..((.((((.......)).)).))..)).....   0.80
((..((.(((((.....))).)).))..)).....  -0.90
((..((.((((((...)))).)).))..)).....  -1.70
((..((((.......)).......))..)).....   6.70
((..((((.............)).))..)).....   4.60
((..((((...((...))...)).))..)).....   6.10
((..((((..((.....))..)).))..)).....   3.30
((..((((..(((...)))..)).))..)).....   2.50
((..((((.((.......)).)).))..)).....   0.90
((..((((.(((.....))).)).))..)).....  -0.80
((..((((.((((...)))).)).))..)).....  -1.60
((..((((((....)).....)).))..)).....   5.50
((..((((((.....))....)).))..)).....   7.60
....((..................)).........   3.60
....((..((....))((....)))).........   8.60
....((..........((....)))).........   6.70
....((......((.......)).)).........   8.50
....((.....((...))......)).........   6.20
....((.....((.........)))).........   6.60
....((.....(((.......))))).........   5.70
....((....((.....)).....)).........   4.00
....((....(((...))).....)).........   3.20
....((...((.......))....)).........   2.00
....((...(((.....)))....)).........   0.30
....((...((((...))))....)).........  -0.50
....((..((....))........)).........   6.30
....((..((.....)).......)).........   8.70
....((..((...........)).)).........   6.60
....((..((.((...))...)).)).........   8.40
....((..((((.....))..)).)).........   6.70
....((..(((((...)))..)).)).........   5.90
....((.((......)).......)).........   7.70
....((.(((....))).......)).........   5.20
....((.((............)).)).........   3.50
....((.((..((...))...)).)).........   5.50
....((.((.((.....))..)).)).........   3.20
....((.((.(((...)))..)).)).........   2.40
....((.((((.......)).)).)).........   1.30
....((.(((((.....))).)).)).........  -0.40
....((.((((((...)))).)).)).........  -1.20
....((((.......)).......)).........   7.20
....((((.............)).)).........   5.10
....((((...((...))...)).)).........   6.60
....((((..((.....))..)).)).........   3.80
....((((..(((...)))..)).)).........   3.00
....((((.((.......)).)).)).........   1.40
....((((.(((.....))).)).)).........  -0.30
....((((.((((...)))).)).)).........  -1.10
....((((((....)).....)).)).........   6.00
....((((((.....))....)).)).........   8.10
```
Their converted energy sum is `p=63.99386456774525`.

The last thing you need is the "partition function=Q", which is the sum of **all** converted energies, which is for the example sequence `Q=237.17169015660585` (scaling should not be necessary, as input is still rather short, i.e. no overflows expected). The probability that bases 5 and 26 form a pair is then simply `p/Q` = `63.99386456774525 / 237.17169015660585` = `0.26982084`

The usual route is using `RNAfold -p` for this type of computation, i.e. `echo CACUGUAAAGCUAACUUAGCAUUAACCUUGACUUU | RNAfold -d2 -p --noPS --noLP`. The resulting `dot.pd` file holds the probabilities in the "ubox table": `cat dot.ps  | grep "^5 26 "` will return `5 26 0.604192188 ubox`, where the value `0.604192188` is the square root of the probabilities, i.e. you need to square it like `0.604192188^2` = `0.3650482000402273`.

Why do both routes not produce the same value?

Could this point to slight discrepancies between inside and outside recurrences, or am I missing something?

System I used:
```
(base) t490s x86_64 >RNAfold --version
RNAfold 2.6.4
```
```
(base) t490s x86_64 ~>uname -a
Linux t490s 5.4.0-189-generic #209-Ubuntu SMP Fri Jun 7 14:05:13 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by RaumZeit** [comment]
Hi Stefan!
You are correct with your computations of the partition function, If I'm not mistaken. The reason why the results predicted by RNAfold and exhaustive computations with RNAsubopt don't yield the exact same solution is due to some internal smoothing of the dangling end contributions for partition function computations. In particular, the following CPP macro is to blame here: https://github.com/ViennaRNA/ViennaRNA/blob/4a0e008b5ed50e4f39e8de93a3a97631eca589b0/src/ViennaRNA/params/params.c#L40
It will slightly alter the dangling end contributions in such a way that the MFE/Subopt energies are not exactly the same as those that end up in the Boltzmann factors. The reason why this is done is that dangling end contributions must always be benefitial, i.e. have energies <= 0. However, when rescaling the parameters to higher temperatures, dangling end contributions might become positive. This will render certain computations difficult, such as heat capacity, where we require a smooth derivative of the partition function. Consequently, all partition function computations smooth out the dangling end contributions such that they reasonably approach 0 for high temperatures...

If you want to check whether a partition function computations really covers the full (RNAsubopt) ensemble, you can turn-off the smoothing. But this is not supported by RNAfold. The RNAlib API, however allows for doing that:
The `vrna_md_t` data structure has an attribute `pf_smooth`, which can be set to 0, see also https://github.com/ViennaRNA/ViennaRNA/blob/4a0e008b5ed50e4f39e8de93a3a97631eca589b0/src/ViennaRNA/model.h#L246.
If you then construct a `vrna_fold_compound_t` with the `vrna_md_t.pf_smooth = 0` setting, dangling end contributions are rather clipped at 0 then smoothed. Hence, subsequent partition function computations should yield the same results compared to exhaustive enumerations.

I hope this is of any help! Let me know if you need more information..

Cheers!

**Comment by RaumZeit** [comment]
On another note, regarding the `--noLP` model setting: The partition function computations only apply the *avoid-isolated-basepairs rule* in parts, while MFE/Subopt computations never yield any isolated base pairs. In fact, the partition function computations only remove base pairs from the conformation space if they can not stack onto any adjacent base pair given the sequence. The ensemble that is covered by the partition function, however, still contains structures that have isolated base pairs, as long as the sequence would allow for forming a stack with an adjacent pair.

We know that this renders any comparison between MFE/Subopt and partition function space difficult. However, a naive approach to correctly treat isolated base pairs in the partition function would require an additional DP matrix of size nxn. We already have some other ideas on how to make both ensembles more similar but this will involve heavy restructuring of the recursions and we didn't find the resources so far to actually start implementing it.

**Comment by sjanssen2** [comment]
Hi Ronny,

many thanks for your elaborate answer. This sheds valuable insight into the internals and is quite of reassuring as you are aware of the discrepancies and put my struggles to an end.

Am I correct, that the `-d` parameter has no impact on the partition function computation? `RNAfold --detailed-help` mentions  `Note that with -d1 and -d3 only the MFE computations will be using this
  setting while partition function uses -d2 setting, i.e. dangling ends will be
  treated differently.`

I quickly repeated my analysis from above, this time allowing lonely base pairs. This diminishes the differences from `~9%` to a tiny `3.429947352251439e-05%`. Thus, I totally agree with your second comment.

Would it be worth adding a summary of your reply somewhere into the documentation or `--detailed-help` message?

**Comment by RaumZeit** [comment]
> Hi Ronny,
> 
> Am I correct, that the `-d` parameter has no impact on the partition function computation? `RNAfold --detailed-help` mentions `Note that with -d1 and -d3 only the MFE computations will be using this setting while partition function uses -d2 setting, i.e. dangling ends will be treated differently.`
In parts, you are correct! `-d1` and `-d3` always default to `-d2`. But `-d0` will turn-off dangling end contributions entirely.

> Would it be worth adding a summary of your reply somewhere into the documentation or `--detailed-help` message?
Yes, this should probably be covered more prominently somewhere in the documentation. I'll add an issue to our internal git server, so that this will be added in the future! ;)
