### ISSUE TITLE
How to use RNAduplex in Python?

### ISSUE THREAD

**Issue by Bjoux2** [ViennaRNA/ViennaRNA#3]
I want to use RNAduplex of the viennaRNA package in python but I cannot find which function I should use.

**Comment by bad-ants-fleet** [comment]
Hi,
I recommend you look at unittests for the scripting languages if you search for examples:
https://github.com/ViennaRNA/ViennaRNA/blob/master/tests/python/test-RNA.py

    def test_duplexfold(self):
        print "testing duplexfold()"
        duplex = RNA.duplexfold(seq1, seq2)
        self.assertEqual(duplex.structure, ".(((.....(((.&)))))).")

**Comment by Bjoux2** [comment]
Thanks, that's really helpful to me. However, the example in the test-RNA.py is a little bit confusing. the name of some functions are short forms.  For example, i want to use RNAplfold of the vinneaRNA package. I scaned the test-RNA.py, and i did not find any plfold-like function or the key worlds in the description of RNAplfold such as 'pair probability'.

**Comment by RaumZeit** [comment]
In order to use the scripting language bindings you need to refer to the RNAlib reference manual (e.g.: http://www.tbi.univie.ac.at/RNA/ViennaRNA/doc/html/index.html). This manual describes the API for (most of) our implementations that are used by the executable programs within the ViennaRNA Package. Functions that have been recently added to the library usually contain a 'SWIG wrapper Notes:' paragraph that describes how this function is accessible from the Perl or Python interface.

However, some of the library functions are not properly wrapped in the scripting language interface (yet). In particular, the algorithms used in RNAplfold are only accessible through the C-library. But the corresponding scripting language wrappers are planned for the future.

As @bad-ants-fleet already pointed out, the unit tests directory already contains several application scenarios where the library functions are used from Perl or Python. If a particular function of the library is not tested in one of the .perl/.py/.py3 scripts it is likely that there is no wrapper for this function yet.
