### ISSUE TITLE
Option to turn off the dotplot

### ISSUE THREAD

**Issue by Florian-H-Lab** [ViennaRNA/ViennaRNA#47]
There is actually no option for RNAfold if you turn on --MEA or -p to turn off the dotplots(.ps). If you have lots of sequences this gets really out of hand rather quickly. Thus, a parameter flag should be included in RNAfold.c to account for this.

**Comment by RaumZeit** [comment]
Hi,
thanks for the suggestion. However, the reason behind the fact that the `--noPS` option doesn't turn-off the dot-plot is that base pair probabilities are served only through the dot-plot. Thus, a combination of `-p` and the updated `--noPS` would not make too much sense as it turns-on computation of the base pair probabilities but omits the corresponding output.

However, I see your point and will make sure that this issue is addressed in the upcoming release.

**Comment by RaumZeit** [comment]
Solved with the new command line option `--noDP` since version 2.4.12
