### ISSUE TITLE
Energy Model closed vs open structure for mismatches RNAeval

### ISSUE THREAD

**Issue by Jogala** [ViennaRNA/ViennaRNA#49]
Hi,

there is a thing in your energy model that confuses me:

Say we have two strands:

5' GGGG 3' and 5' CCGG 3'

Now say i give RNAeva the conformation

GGGG&CCGG
..((&))..

which yields 

dG(37) =  -0.80

I can reproduce that result applying the Turner rules:

dG_terminal_mismatch + dG_wc + dG_initation = -1.6 - 3.3 +4.1 = -0.8

But if I set 

GGGG&CCGG
((((&))))

RNAeval yields

dG(37) =  1.20

I don't understand what value you are assigning to (( )) on the GG/GG's. There is no equivalent for that in the Turner rules as far as I know. Is it a fit parameter for better secondary structure prediction? What is the rule / logic you are applying here  for calculating the energy for this kind of structure?

**Comment by RaumZeit** [comment]
Hi,
non-canonical base pairs such as stacks of GG/GG are allowed in RNAeval and may be even forced in RNAfold.
The parametrization, however, is another issue. Mostly, because there are no official parameters for non-canonical base pairs. Thus our implementations follow the simple rule to take the worst energy contribution of the most similar canonical base pairs.

While this may seem odd at first, we chose this behavior on purpose for consensus structure prediction. Here, multiple aligned sequences may form a base pair by majority voting, but some of the sequences don't allow for a canonical interaction. So instead of adding an additional penalty or leaving those sequences out, we decided to use the rule outlined above.
As a consequence, this also applies for single sequences (at least if you want to evaluate structures with non-canonical base pairs, or if you enforce non-canonical base pairs through constraints).

I hope this clarifies your question...

Btw.: Using `RNAeval -v` you get a detailed output of the individual loop energies, which in your example looks like this:
```
echo -en "GGGG&CCGG\n((((&))))\n" | RNAeval -v
WARNING: bases 1 and 8 (GG) can't pair!
WARNING: bases 2 and 7 (GG) can't pair!
External loop                           :    50
Interior loop (  1,  8) GG; (  2,  7) GG:   130
Interior loop (  2,  7) GG; (  3,  6) GC:  -140
Interior loop (  3,  6) GC; (  4,  5) GC:  -330
Hairpin  loop (  4,  5) GC              :     0
GGGG&CCGG
((((&)))) (  1.20)
```
Here, the 1.3kcal of the GG/GG stack originate from the closest canonical stack with highest free energy, which is GG/UU with 1.3kcal/mol...

**Comment by RaumZeit** [comment]
A description of this behavior can also be found in section **Modifying the energy parameters of the model** of the [ViennaRNA Package 2.0 publication](https://almob.biomedcentral.com/articles/10.1186/1748-7188-6-26) where we state:

*The current implementation assumes that the energy contribution of a loop with non-standard base pairs or non-standard nucleotides equals the least stabilizing contribution from the same loop type with canonical nucleotides and pairs only.*

**Comment by Jogala** [comment]
Hej guys thanks a lot for your help! Sorry that I did not respond earlier.

How do you determine the "most similar canonical base pairs"? 

What is closest to AG\GA?

Best 

Joachim

**Comment by RaumZeit** [comment]
In this case, both base pairs are non-canonical, so both of them are treated the same internally. Consequently, since we do not distinguish one non-canonical base pair from another, the resulting free energy should be the least favorable stacking interaction available in the parameters, i.e. GU pair on top of GU pair, which yields 1.3kcal/mol. On top of that, our implementation adds another 0.5kcal/mol per strand-end as 'TerminalAU' penalty. So in total, this should be 2.3kcal/mol.

This might be too harsh in this context, but that's how the implementation works at the moment.
