### ISSUE TITLE
RNAcofold -p option in Python API

### ISSUE THREAD

**Issue by KarenVS** [ViennaRNA/ViennaRNA#52]
Hi,
I'd like to calculate the binding energy between two hybridized sequences in Python. I've looking for a method in the API to calculate the Delta G value for heterodimer binding, as obtained by calling RNAcofold from the command prompt with -p option. So far, I found  `pf_dimer()` and `co_pf_fold` but neither return this value:
```
sequence1="AUGAUGCGCUGCCCUUUCUGUCGUCAUUCAGCGCAUACCCGCACCAGCCGGUAUGUGAGUGACAAUGUCAAAGAAAGUUAUCUCCAGUGCCAGAAUAUUUACUGUUCGGCGACAUUUAAAACGCAUGAGUCAAUUUGUGCCGUGAUUCGUUCUCCGGUCACGGAGGAAAAACCAGCACCGGCAAGCACAGCACCGGCUGUUGUCCGAAAAGUUAAAGGCUGUUACAGCUCACCAUUCAACCAUU"
sequence2="ACGACAGAAAGGGCAGCGCAUCAU"
fc = RNA.fold_compound(sequence1 + "&" + sequence2)
(structure, mfe) =fc.mfe_dimer()
(x,ac,bc,fcab,cf) = fc.pf_dimer()
```
or 
`RNA.co_pf_fold(sequence1 + "&" + sequence2)`

 Any guidance would be greatly appreciated :)

**Comment by RaumZeit** [comment]
Dear KarenVS,

both versions `fc.pf_dimer()` and `RNA.co_pf_fold()` return the same data structure that contains the  free energy
- of the full ensemble in `cf`
- of connected ensemble `fcab`
- of monomer `A` ensemble `ac`, and
- of monomer `B` ensemble `bc`

The problem here is that for two sequences `A` and `B` with lengths `n` and `m` our current implementation is lazy and doesn't distinguish between connected and unconnected states during the recursions to compute the partition function `Q_{1, n + m}`. We rather correct our computations in a post-processing step. Thus, the ensemble free energy `-kT ln (Q_{1, n + m}` represents a mixture of different ensembles, and we need some further computations to obtain the binding energy.

First, we substract all unconnected states over the full-length duplex sequence, since they were erroneously added to `Q_{1, n + m}`. Thus

    QcAB = (Q_{1, n + m} - Q_{1, n} * Q_{n + 1, n + m}) * exp( -duplex_init / kT)

where `duplex_init` is the duplex initiation energy, `k` the Boltzmann constant and `T` temperature. From that we derive

    fcab = -kT ln(QcAB)

Still, the resulting value contains contributions from the single monomer ensembles of `A` and `B`, `QA = Q_{1, n}` and `QB = Q_{n+1,m + m}`, respectively. Those are stored as ensemble free energies

    ac = -kT ln(QA)

and

    bc = -kT ln(QB)

Finally, we can compute the true delta G binding energy

    dG = fcab - ac - bc

and the partition function of the total ensemble of all monomers and dimers

    QAB = QcAB + Q_{1, n} * Q_{n + 1, n + m}

which we already return as ensemble free energy

    cf = -kT ln(QAB)

I hope this explanation is helping

Best,
Ronny

**Comment by RaumZeit** [comment]
Since there has been no update for this question, I'm closing this issue for now.

Please feel free to re-open if any problems or questions remain.
