### ISSUE TITLE
how to interpret the output file from RNAalifold?

### ISSUE THREAD

**Issue by yixuan0816** [ViennaRNA/ViennaRNA#57]
I would like to know the information of every column in alifold.out. Could you please let me know column names of the output file?

For example: 
RNA-Tutorial/Data/genefinding/rnaz/human/x/results/locus6/alifold.out

6 sequence; length of alignment 116
alifold output
   13    63  0  87.5%   0.709 GC:6   
   14    62  0  87.5%   0.677 GC:6   
   12    64  0  87.5%   0.611 AU:6   
   11    65  0  87.5%   0.490 GC:6   
   23    51  0  82.3%   0.776 GC:6   
   24    50  0  82.2%   0.843 AU:6   
...

I am thinking the first column and the second column represent the nth nucleotide. The third column represents the likelihood of the pair. The last column represents compensatory mutations and the number of events. What are 3rd and 5th columns?

Thank you!

**Comment by RaumZeit** [comment]
Hi,
indeed, the `alifold.out` file contains information on the base pair probabilities, where the first two columns represent the alignment-columns `i` and `j` that may for the base pair `(i, j)`, and the fourth column is the corresponding probability `p_ij`.

The third column contains the number of counter-examples, i.e. how many sequences in the alignment can not form this canonical base pair.

The fifth column contains a pseudo-entropy for base pair `(i,j)`, i.e.:
```
S(i, j) = S_i + S_j - p_ij ln(p_ij)
        = - \sum_k p_ik log(p_ik) - \sum_k p_jk log(p_jk) - p_ij log(p_ij)
```
where `p_ij` is the base pair probability for pair `(i, j)`.

Starting with column 6, we list the different pairs observed for these two alignment columns, e.g. 6 GC pairs if it states `GC:6`. Since there are 6 different canonical pairs available (`GC`,`CG`,`AU`,`UA`,`GU`,`UG`) there may be at most 11 columns in total.

I hope this explanation is helping.

P.S.: I'll see that we include such a description into the man page for the `RNAalifold` program in one of the next releases.

**Comment by yixuan0816** [comment]
Very helpful and informative! Thank you!!!
