### ISSUE TITLE
How to reproduce tutorial codes in python?

### ISSUE THREAD

**Issue by Shunsuke-1994** [ViennaRNA/ViennaRNA#58]
Hello! I want to reproduce this tutorial code using python API but I couldn't find how to calculate MEA structure, the frequency of mfe structure and the diversity.

```
$ RNAfold -p --MEA < test.seq
  CUACGGCGCGGCGCCCUUGGCGA
  ...........((((...)))). ( -5.00)
  ....{,{{...||||...)}}}. [ -5.72]
  ....................... {  0.00 d=4.66}
  ......((...))((...))... {  2.90 MEA=14.79}
  frequency of mfe structure in ensemble 0.311796; ensemble diversity 6.36
```

**Comment by RaumZeit** [comment]
Hi,
I'm afraid that at this time you can't reproduce all the above computations from within the Python interface.
In particular, the function(s) to compute the MEA structure are not properly wrapped to Python/Perl just yet. Also, the C-library provides a convenience function to compute the probability of any structure in the ensemble `vrna_pr_structure()` which is not wrapped at the moment as well. However, you can compute probabilities quiet easily using the ensemble free energy returned by the partition function computations, since `p(s) = exp(-E(s)/kT) / Z` where `Z` is the partition function. Note, that the partition function computation returns the ensemble free energy `dG = -kT ln(Z)`.

Here is some Python code to reproduce everything but the MEA structure for the above example:
```.py
from __future__ import print_function
import math
import RNA

sequence = "CUACGGCGCGGCGCCCUUGGCGA"

# create a fold_compound object for the current sequence
fc = RNA.fold_compound(sequence)

# compute the MFE and corresponding structure
(mfe_struct, mfe) = fc.mfe()

# re-scale the Boltzmann factors to avoid overflows in partition function computations
fc.exp_params_rescale(mfe)

# compute partition function
(bp_propensity, dG) = fc.pf()

# compute centroid structure
(centroid_struct, centroid_dist) = fc.centroid()
centroid_energy = fc.eval_structure(centroid_struct)

# compute frequency of MFE structure (the 'hard' way)
kT = RNA.exp_param().kT / 1000.

prob_mfe = math.exp((dG - mfe) / kT)

# compute ensemble diversity, i.e. mean base pair distance
ensemble_div = fc.mean_bp_distance()

# Finally, print everything:

print("%s\n"
      "%s (%6.2f)\n"
      "%s [%6.2f]\n"
      "%s {%6.2f d=%6.2f}\n"
      "frequency of mfe structure in ensemble %g; "
      "ensemble diversity %6.2f" %
      (sequence,
       mfe_struct, mfe,
       bp_propensity, dG,
       centroid_struct, centroid_energy, centroid_dist,
       prob_mfe,
       ensemble_div))
```
This will give you the following output:
```
CUACGGCGCGGCGCCCUUGGCGA
...........((((...)))). ( -5.00)
....{,{{...||||...)}}}. [ -5.72]
....................... {  0.00 d=  4.66}
frequency of mfe structure in ensemble 0.311796; ensemble diversity   6.36
```

**Comment by Shunsuke-1994** [comment]
Very helpful. Thank you!
