### ISSUE TITLE
--enable-shared --disable-static fail to enable shared libraries

### ISSUE THREAD

**Issue by yurivict** [ViennaRNA/ViennaRNA#61]
OS: FreeBSD 12

**Comment by RaumZeit** [comment]
Could you please be a bit more specific and include exact configure options and the corresponding output for the failed build? Also, please state which version is affected!

Using both of the configure options `--enable-shared --disable-static` seems to work for me on latest development branch and Linux...

**Comment by yurivict** [comment]
Version: 2.4.13
Log: https://people.freebsd.org/~yuri/viennarna-build.log
Configure args: ```--enable-shared --disable-static --with-gsl --with-cluster --with-kinwalker --enable-mpfr --without-python --without-python3 --without-perl --x-libraries=/usr/local/lib --x-includes=/usr/local/include --prefix=/usr/local```
OS: FreeBSD

It builds static libraries:
```
lib/libRNA.a
lib/libg2.a
```

**Comment by RaumZeit** [comment]
Ok, I realize the problem now. It builds with the `--enable-shared --disable-static` sections but still builds static libraries.

Unfortunately, I have to tell you that at least for `libRNA` this is actually an intended behavior. Our automake implementation does not allow for building a shared library, since we believe that our API/ABI is not stable enough at this moment.
Throughout the entire versions 2.x we started to transition to at least a stable API, but the ABI still changes a lot. Furthermore, version 2.x is fully backwards compatible with 1.x so the complete API is a little bit inconsistent right now. Therefore, we decided to wait for release of version 3 to officially support a shared library version for our implementations.
Due to all the above current drawbacks of our library, we don't see any benefits from having a shared `libRNA` library, as all dependent programs need to be recompiled with each version update anyway...

For the other library, `libg2`, I don't have such a concise answer. In fact, it is only used by the `RNAforester` program, which is not actively maintained anymore. We ship, however, the latest version available. Maybe, the build instructions in the `src/RNAforester` subdirectory can be patched such that the `RNAforester` program links against the shared library instead of the static one? If you know of an easy way to change that, please let me know. PR are of course welcome!

I hope this answers your question.

**Comment by yurivict** [comment]
> Our automake implementation does not allow for building a shared library, since we believe that our API/ABI is not stable enough at this moment.

I have asked from the perspective of having a package. I maintain the FreeBSD package, and there is a policy that packages are required to only build shared libraries. Otherwise, using static libraries increases the size of binaries that use static libraries, because the same compiled code would be copied into multiple executable, and therefore would be duplicated.

**Comment by RaumZeit** [comment]
Yes, I totally agree with your point regarding the increased executable sizes due to redundant binary code.
However, I just had a look at our libtool/automake configurations and it seems that it requires some effort to actually enable shared library support. In fact, the largest problem is generating a list of all the symbols to be exported and a proper versioning for the resulting `libRNA.so`.
Therefore, I can't provide you with a patch at this time. Feel free to change our automake rules in `src/ViennaRNA/Makefile.am`. I can't tell you for sure what needs to be done to enable shared libraries, but it might be sufficient to change the line
```
libRNA_la_LDFLAGS = -avoid-version -static $(LTO_LDFLAGS) $(PTHREAD_LIBS)
```
to something like
```
libRNA_la_LDFLAGS =  -export-symbols=symbol_list.txt $(LTO_LDFLAGS) $(PTHREAD_LIBS)
```
where `symbol_list.txt` is a text file containing each symbol to export. Maybe, even a
```
libRNA_la_LDFLAGS =  -export-symbols-regex '*' $(LTO_LDFLAGS) $(PTHREAD_LIBS)
```
works? I've never tested that, though. Also, as I mentioned before, one has to take care of version numbers for the dynamic libraries. These need to be set with the `-version-info` parameter...
Anyway, I assume that once we officially start building our own shared libraries and corresponding versions, there might easily be an inconsistency between the versions you would provide and those that we officially assign. So I actually would advise against adding version numbers.

As you can see, it might be a tedious task to switch to a shared library for the FreeBSD Package.
Maybe, you can convince some of the FreeBSD maintainers to let you package the statically linked binaries after all? This would be the easiest solution. Also, stripping the executable binaries from unused symbols already greatly reduces their size. Our statically linked executables for Fedora, for instance, only require approximately 1MB per program and the number of programs is less than 30.
