### ISSUE TITLE
call pf_fold with --gquad in API

### ISSUE THREAD

**Issue by avilella** [ViennaRNA/ViennaRNA#64]
What is the equivalent of calling RNAfold with the `--gquad` option in the API (Python, Perl)?

E.g.
```
echo AGAGAGGGGAGGGGAGGGGAAGAGAGGGGAGGGGAGGGGAAGAGAGGGGAG | RNAfold --gquad --noconv --noPS --MEA -d2 -P /usr/share/ViennaRNA/dna_mathews2004.par
```
Thanks in advance.

**Comment by RaumZeit** [comment]
This is not easily accomplished with the 'flat' Python/Perl interface. But one can use the object-oriented interface that works on `fold_compound` objects. Note, however, that MEA structures can not be computed from the scripting language interface yet.

But more importantly, please note, that the G-Quadruplex energy model was fitted against UV-melting data for RNA G-Quadruplexes (https://dx.doi.org/10.1109/TCBB.2013.7)! There are no equivalent DNA parameters available at the moment, and it is not obvious whether the simplified model we apply for RNAs can actually be applied for DNA sequences as well.

Nevertheless, the Python code below should accomplish your task (except for MEA computation)

```.py
import RNA

seq = "AGAGAGGGGAGGGGAGGGGAAGAGAGGGGAGGGGAGGGGAAGAGAGGGGAG"

# read DNA parameters
RNA.read_parameter_file("/usr/share/ViennaRNA/dna_mathews2004.par")

# get model details data structure
md = RNA.md()

# set G-quadruplex flag in model details
md.gquad = 1

# create fold_compound data structure (required for all subsequently applied  algorithms)
fc = RNA.fold_compound(seq, md)

# compute MFE and MFE structure
(mfe_struct, mfe) = fc.mfe()

# rescale Boltzmann factors for partition function computation
fc.exp_params_rescale(mfe)

# compute partition function
(pp, pf) = fc.pf()

# compute centroid structure
(centroid_struct, dist) = fc.centroid()

# compute free energy of centroid structure
centroid_en = fc.eval_structure(centroid)

```

**Comment by avilella** [comment]
Thanks for the reply.

There are some G-quad experts here in Cambridge (UK) who could maybe help
with the parameters for DNA G-quad prediction, I wonder if we could connect
the dots together to feed a sensible G-quad DNA model into Vienna RNA?

What format would it need to look like?

**Comment by RaumZeit** [comment]
That would be great. For the RNA G-Quadruplexes, we've used a set of melting temperatures for about 25 short G-Quadruplex sequences obtained from UV-melting. From this we can determine free energies, enthalpies and entropies for the G-Quadruplex fold which eventually were used to fit our simple energy model.

Basically, we fit a model
```
E(T, L, l) = a(T) * L + b(t) * log(l - 2)
```
where `T` is the temperature, `L` is the number of layers, and `l` is the total linker length, i.e. the number of nucleotides in the short sequences connecting the G-runs. This model assumes that the stability of the G-Quadruplex only depends on the number of layers `L` (enthalpic contributions) and the total length `l` of the linker sequences (entropic penalty). `a(T)=H_a + T*S_a` and `b(T)=H_b + T*S_b` have been fitted to experimental melting data under the assumption that `S_a=0` and `H_b=0`, i.e. stacking between layers is purely enthalpic, and contribution of the linker sequences is purely entropic.

For RNAs this model seems to work fine since most of the RNA G-Quadruplexes tend to adopt the same parallel conformation. But for DNA, many different conformations have been observed. So it would be interesting, whether one can fit our RNA model using DNA melting data. If this doesn't work out, it might be that only slight changes are required to adopt the model? This needs to be explored.

So as soon as we get our hands to some thermodynamics data for DNA G-Quadruplexes we could start setting up a corresponding model. I would definitely be interested in something like that!
