### ISSUE TITLE
[inquiry] energy sets as part of the lib for file-independent loading

### ISSUE THREAD

**Issue by martin-raden** [ViennaRNA/ViennaRNA#65]
Hi @RaumZeit 
again and again I am running into the problem that I would like to switch to a non-default energy parameter set (like Turner99) without providing the file, e.g. when setting/switching parameters within a VRNA-based tool like IntaRNA without knowing where the files are installed/stored/whatever..

My suggestion:
- include the parameter files as strings into the C library, each with an appropriate name
- provide a function (analogously to the parse-from-file-function) to load parameters from a respective string
- that way, one could switch the energy parameters via the API from within the lib and still be able to load (customized) sets from file (for whoever is going to mess with these things..)

I could think about and help with the implementation.

Thanks and best,
Martin

**Comment by RaumZeit** [comment]
Hi Martin,
this is definitely a good idea, even though I am a little bit worried about the consequential size increase of RNAlib! But as long as nobody complains about approx. 10MB larger `libRNA.a`,
I'll keep the parameter files as strings. Otherwise, I will think about storing them blobs...

I've already implemented a function `vrna_params_load_from_string()` which (i) parses a string in ViennaRNA parameter file format, and (ii) adjusts the energy parameters accordingly. Some convenience functions to load the parameter files shipped with the ViennaRNA Package have also been implemented (`vrna_params_load_RNA_Turner1999(), vrna_params_load_RNA_Andronescu2007()`, etc.).

The additional functions will be available with the next release v2.4.14

**Comment by martin-raden** [comment]
many thanks, sounds splendid! :+1:

**Comment by martin-raden** [comment]
@RaumZeit 
to keep the main lib small you could:
- put the strings into a new sublib, which can be included optionally
- put the strings into headers only, thus tools that want to use that feature will include them (and only the ones of interest) and thus blow-up their binaries

**Comment by RaumZeit** [comment]
Thanks for the recommendations!
I've included the energy parameter strings within the library now, but do not expose them as such. The parameters can only be loaded through wrapper functions as described above...

Since I just released the new version 2.4.14 which includes this feature, I'll close the issue now. Feel free to re-open, if anything is still unclear :)

**Comment by martin-raden** [comment]
Hi @RaumZeit 
wonderful, is working fine.. **BUT**  it would superduper to be able to 
- get the name of the current parameter data setup (`last_parameter_file()` come closest but is deprecated and returns NULL for default model)
- that way also get a name of the default model
- have static const char* of the parameter set names (instead of the hard coded strings) to check whether a certain parameter set was already loaded (per default) or not (to avoid reload of default model if changed somewhen in the future)

- given access to the name, one could store/print the used parameter set along with the output to ensure reproducability!!

What do you think? too much of an overhead or worth it? That way,

**Comment by martin-raden** [comment]
@RaumZeit : PS. cannot reopen the issue as you suggested once.. ;)

**Comment by martin-raden** [comment]
btw. with fixed (short) IDs, you could also make `-p DNA` replaced by eg `-p Turner99` etc. to load respective stuff.. 

just an idea. ;)
