### ISSUE TITLE
expose "vrna_pf_dimer_concentrations" via SWIG

### ISSUE THREAD

**Issue by martin-raden** [ViennaRNA/ViennaRNA#66]
@RaumZeit 
it would be highly appreciated, if you could expose the `vrna_pf_dimer_concentrations` function and data types within the python interface with the next release.

Many thanks,
Martin

**Comment by RaumZeit** [comment]
This should already be possible using the function
```
RNA.get_concentrations()
```
However, instead of returning the data structure `vrna_dimer_conc_t` of the C interface, it returns a tuple of values that represent this data structures attributes, i.e.:
```
(AB,AA,BB,A,B) = RNA.get_concentrations(fcab, fcaa, fcbb,ac, bc, startA, startB)
```
where `AB`, `AA`, `BB`, `A`, and `B` are the end concentrations for the hetero- and homo dimers, as well as the monomers...

**Comment by martin-raden** [comment]
*thumbsup* will give it a try! sorry for missing it.. ;)
