### ISSUE TITLE
How to extract the pair probabilities from *_dp.ps file using mountain.pl?

### ISSUE THREAD

**Issue by bakerwm** [ViennaRNA/ViennaRNA#78]
I am not sure my understanding is correct about the pair probabilities, parsed from `*_dp.ps` file using `mounttain.pl` script. 

**my understanding**
According to the descritpion of `mountain.pl` script: the definition of pair probabilities for base i is the **mean pair probabilities** enclosing the base i. But the `mountain.pl` count the **sum** instead!? This is the reason why `mountain.pl` failed to process `RNAplfold` output `*_dp.ps`. is this correct?

```
$ RNAplfold -W 70 -u 28 < 5S.seq # output files: 5S_dp.ps, 5S_lunp
$ ./ViennaRNA-2.4.14/src/Utils/mountain.pl 5S_dp.ps
Can't take log of -0.036633 at ./ViennaRNA-2.4.14/src/Utils/mountain.pl line 66, <> line 385.
```

The script:
```
# line-66 of mountain.pl
    $sp[$i] += (1-$pp[$i])*log(abs(1-$pp[$i]));
```

The description in `moutain.pl` script:

```
# produce Pauline Hogeweg's mountain representation *_dp.ps files
# writes 3 sets of x y data separated by a "&"
# the first two sets are mountain representations from base pair probabilities
# and mfe structure, respectively.
# definition: mm[i],mp[i] = (mean) number of base pairs enclosing base i
# third set a measure of well-definedness: the entropy of the pair probs of
# base i, sp[i] = -Sum p_i * ln(p_i). Well-defined regions have low entropy.
 
```

**Comment by RaumZeit** [comment]
Hi @bakerwm ,

the problem you are facing here is due to the fact, that the individual base pair probabilities in the output of `RNAplfold` for one particular nucleotide do not sum up to 1! This is attributed to the fact that in `RNAplfold` the windowing effect includes base pairs of, say position `i` with other bases that do not occur in the same window. Hence, the sum of probabilities of all base pairs that involve `i` can easily exceed the value of 1. The actual error, the `mountain.pl` script raises is then in the computation of the positional entropy, that requires not only the probability `p_i` of position `i` to be paired, but also the probability `q_i = 1 - p_i` of this position to be unpaired. Now, since this probability may be larger than 1, `q_i` can become negative, and computing the logarithm of a negative number is not possible.
If you still want to use this script to process the `RNAplfold` output, you can change line 66 such that you first check whether `1 - $pp[$i] > 0`, for instance:
```
$sp[$i] += (1-$pp[$i])*log(abs(1-$pp[$i])) if $pp[$i] < 1;
```
This way, the error won't occur. However, the resulting values in the mountain plot will still be inconclusive due to the mixture of probabilities of the different folding windows of `RNAplfold`.
