### ISSUE TITLE
VRNA_CONSTRAINT_DB_ENFORCE_BP not working

### ISSUE THREAD

**Issue by caseypie** [ViennaRNA/ViennaRNA#80]
In the document it says:

> 16.12.3.2 VRNA_CONSTRAINT_DB_ENFORCE_BP
> #define VRNA_CONSTRAINT_DB_ENFORCE_BP 32768U
> #include <ViennaRNA/constraints/hard.h> Switch for dot-bracket structure constraint to enforce base pairs.
> This flag should be used to really enforce base pairs given in dot-bracket constraint rather than just weakly-enforcing them.

However, I failed to enforce round bracket constraints on my sequence folding via

vrna_hc_add_from_db (fc, cons, VRNA_CONSTRAINT_DB_ENFORCE_BP ).

Instead, it just totally ignores the constraints. On the other hand, if I use VRNA_CONSTRAINT_DB_RND_BRACK or VRNA_CONSTRAINT_DB_DEFAULT, it only "weakly" enforces the pair I assign -- the basepairing probability increases but still not 1.

Below is my test code:

#include <stdlib.h>
#include <stdio.h>
#include <string.h>

#include <ViennaRNA/fold_compound.h>
#include <ViennaRNA/constraints/basic.h>
#include <ViennaRNA/constraints/hard.h>
#include <ViennaRNA/part_func.h>
#include <ViennaRNA/utils/basic.h>

int main()
{
  /* The RNA sequence */
  char      *seq = "GAGUAGUGGAACCAGGCUAUGUUUGUGACUCGCAGACUAACA";
  vrna_fold_compound_t  *fc = vrna_fold_compound(seq, NULL, VRNA_OPTION_DEFAULT);
  char *cons = "..(......................................).";
  vrna_hc_add_from_db (fc, cons, VRNA_CONSTRAINT_DB_ENFORCE_BP);

  char      *propensity = (char *)vrna_alloc(sizeof(char) * (strlen(seq) + 1));
  float en = vrna_pf( fc, propensity);;
  
  printf("%s\n%s [ %6.2f ]\n", seq, propensity, en);

  free(propensity);

  return 0;
}

**Comment by RaumZeit** [comment]
Dear @caseypie,
it seems you are using the options for the function `vrna_hc_add_from_db()` wrongly. I just tested your code snippet, and it works perfectly, if you change the line
```
vrna_hc_add_from_db (fc, cons, VRNA_CONSTRAINT_DB_ENFORCE_BP);
```
to
```
vrna_hc_add_from_db (fc, cons, VRNA_CONSTRAINT_DB_DEFAULT | VRNA_CONSTRAINT_DB_ENFORCE_BP);
```
Note, that options passed to most of our functions are simple bit vectors. So to combine multiple options, you need to logically combine them, for instance with the or `|` operator.

As a side note, you constraint is one nucleotide longer than the input sequence. While this is not so much of a problem, since the last nucleotide of the constraint is unpaired anyway, I strongly suggest that you always check whether both, sequence and constraint have the same length.
