### ISSUE TITLE
Energy values are not always clear 

### ISSUE THREAD

**Issue by aerijman** [ViennaRNA/ViennaRNA#81]
Hi, How is this scenario possible:

from Vienna package docs:
```
$ RNAsubopt -e 1 -s < test.seq
CUACGGCGCGGCGCCCUUGGCGA   -500    100
...........((((...)))).  -5.00
....((((...))))........  -4.80
(((.((((...))))..)))...  -4.20
...((.((.((...)).)).)).  -4.10
```

more specifically:
```
....((((...))))........  -4.80
(((.((((...))))..)))...  -4.20

```

If not because of pseudo knots, how is it possible that a same structure with 3 bonds less has a more negative free energy? This is just one case but I repeatedly see this type of scenarios. I posted a question about a similar question a long time ago [HERE](https://bioinformatics.stackexchange.com/questions/7460/how-is-that-ensemble-free-energy-is-lower-than-the-mfe-in-rnafold-from-viennarna). 

Please, excuse me if I am not being aware or misinterpreting a basic concept here and I will be glad to hear back from you to learn more about. My goal is to understand these results.

**Comment by bad-ants-fleet** [comment]
Hi aerijman,

The title of your post is misleading, the resulting values do make sense. The ViennaRNA package uses a thermodynamic energy model where the free energy of every loop contributes to the energy of the overall structure. That is *not* a maximization of base-pairs! For example, a single base-pair that closes a hairpin loop is typically not favorable due to the entropy cost of a closed loop relative to a flexible unpaired region. It needs a few more stacked base-pairs that form that well-known double-helix structure to form a stable hairpin structure. What you observe in the above example is a similar effect but with a different type of loop.

I would recommend you read up on the nearest neighbor energy model as well as on some related concepts, you may want to start here:
https://www.tbi.univie.ac.at/RNA/ViennaRNA/doc/html/energy_evaluation.html

If you want to see how much every loop contributes to the structure, see the output of
RNAeval -v:

```
$ RNAeval -v

Use '&' to connect 2 sequences that shall form a complex.
Input sequence (upper or lower case) followed by structure; @ to quit
....,....1....,....2....,....3....,....4....,....5....,....6....,....7....,....8
CUACGGCGCGGCGCCCUUGGCGA
(((.((((...))))..)))...

length = 23
External loop                           :   -40
Interior loop (  1, 20) CG; (  2, 19) UG:  -210
Interior loop (  2, 19) UG; (  3, 18) AU:  -100
Interior loop (  3, 18) AU; (  5, 15) GC:   300
Interior loop (  5, 15) GC; (  6, 14) GC:  -330
Interior loop (  6, 14) GC; (  7, 13) CG:  -340
Interior loop (  7, 13) CG; (  8, 12) GC:  -240
Hairpin  loop (  8, 12) GC              :   540
CUACGGCGCGGCGCCCUUGGCGA
(((.((((...))))..)))...
```

**Comment by aerijman** [comment]
Hi Stefan,

Thank you for the reply and explanations and my apologies if the title is misleading (I changed it, although I think that it might still be too broad).

You answered my first question.

My remaining question is, as I asked [HERE](https://bioinformatics.stackexchange.com/questions/7460/how-is-that-ensemble-free-energy-is-lower-than-the-mfe-in-rnafold-from-viennarna), how the ensemble can have lower free energy than the MFE? 

Thank you again and I hope that my inquiries can also be helpful to you.

Also, It would be useful to provide units for the values reported in the ViennaRNA tools (e.g I don't know what is the number in the last column of RNAeval. ), without assuming that users are experts in the field.

**Comment by s-will** [comment]
Hi @aerijman ,

Having lower ensemble energy than mfe is not at all specific to the Vienna RNA package, but a consequence of the general definitions of MFE and ensemble energy in physics.  Anyway, briefly: ensemble energy has to be <= MFE, because the partition function is >= the Boltzmann weight of the MFE.

To your final remark: in non-interactive mode, RNAeval (like most tools of the package) omits the energy unit to keep the output terse. The energy unit is given in the documentation, e.g. see man page of RNAeval: The energy unit is kcal/mol...

**Comment by RaumZeit** [comment]
Hi @aerijman,
I can only join the statements of @s-will and @bad-ants-fleet.
The nearest neighbor energy model is not simply counting the number of base pairs, but all positive and negative contributions to the free energy that arise from base pair stacking and the loss of degrees of freedom in spatial arrangements do contribute to the total free energy. To understand how this works in detail, I refer you to the Nearest Neighbor Data Base (https://rna.urmc.rochester.edu/NNDB/) and other related publications.
Regarding the ensemble free energy G, the answer of @s-will is absolutely correct. Since you can derive it from the partition function Z as G=-RT ln Z, it must be less or equal to the minimum free energy. Afterall, Z = sum_s exp(-E(s) / RT), where s are all structures of the ensemble. I refer you to other publications in the area of RNA secondary structure prediction.
Finally, the units of the predicted energies are not part of the output of our programs mostly due to machine and human readability. The manpages of our programs always state what the units are, so please have a look at them as well.
