### ISSUE TITLE
How do I run RNAduplex (intermolecular base pairs only) on a fold_compound object?

### ISSUE THREAD

**Issue by reisalex** [ViennaRNA/ViennaRNA#89]
The fold_compound object is my preferred way of handling folding calculations in Python as I have better control over constraint adding, model parameters and the results are "complete" (RNA.duplex(seq1,seq2) gives an incomplete structure). I can do a `fc_obj.mfe_dimer()` calculation, but that is the equivalent on RNAcofold (inter + intra-molecular base pairs). How can I achieve the RNAduplex calculation with the fc_obj?

I've tried adding hard constraints, such as ">"*len(seq1) + "<"*len(seq2), the syntax that would theoretically enforce base pairs across sequences, but these cause issues and even code-crashing errors. I saw a closed issue that pointed to the RNA.duplex() function, however RNA.duplex provides only a partial structure, but I would ideally like a complete end-to-end representation of the structure so that I know where it is actually located along my RNA sequences.

**Comment by RaumZeit** [comment]
Unfortunately, we do not provide a `fold_compound` version of the `RNAduplex` algorithm yet. However, this is in planning and the transition of the underlying code is already work in progress.
As of now, your only option is to actually use the `mfe_dimer()` trick that you already found out about. Just for the record, you should use the constant `RNA.CONSTRAINT_DB_INTERMOL` instead of the number 4194304. This will ensure compatibility to future versions, where the flags values might change, but the actual identifier of the flag will stay the same...
