### ISSUE TITLE
backtracking fails during running RNAalifold

### ISSUE THREAD

**Issue by Shunsuke-1994** [ViennaRNA/ViennaRNA#96]
Hi. 
I am using RNAalifold. And I found the backtracking fails when I input many sequences.
For example, I can successfully run RNAalifold for 10000 sequences, but not for 20000 sequences. 

![image](https://user-images.githubusercontent.com/35675972/95661641-d81b3500-0b6b-11eb-8d00-9892b2659163.png)

Do you know what causes this error?

Shunsuke

**Comment by Shunsuke-1994** [comment]
After checking my file, there seems some problematic sequences. 
Please let me close this issue for a moment. 
Sorry.

**Comment by Shunsuke-1994** [comment]
I created another stockholm file containing many sequences(~20000 sequences) and confirmed this error. 
Let me reopen this issue.
Does anybody know how to solve this error?

**Comment by RaumZeit** [comment]
Would you please provide me the alignment that fails for you? You can either send it by email to rna@tbi.univie.ac.at or upload it here in github. I will have a look at it as soon as possible. Generating another random alignment with 20000 sequences still worked for me, though. So I need something that reproduces the problem to actually find the cause...

**Comment by Shunsuke-1994** [comment]
I sent an e-mail with the code and the files.
Thank you.

**Comment by RaumZeit** [comment]
Thank you very much for sending the files!
I've already located the problem and prepared a patch which will be included in the upcoming version 2.4.16.

In brief, the input 20000 sequence alignment you sent me contains a special case in column 429 and column 460. Both enclose parts that are almost always gapped entirely, but the flanking nucleotides may still pair. The algorithm then tries to pair both columns yielding an artificially high free energy due to the violation of the minimum hairpin length restriction in the majority of the sequences. In your case, this high energy contribution exceeded our internal representation of infinite energy, thus for the paired columns in question, the algorithm chose infinity as a minimum. This would usually not be problematic, but our implementation unfortunately also added a covariance term to this contributions, leading to a failure in backtracing.

**Comment by Shunsuke-1994** [comment]
Thank you for your help:)

That really makes sense. 
I look forward to the next version!

Best,
Shunsuke
