### ISSUE TITLE
What versions of gmp and mpfr is the current macOS binary compiled against?

### ISSUE THREAD

**Issue by richardkmichael** [ViennaRNA/ViennaRNA#98]
This is request, and not a bug report.  I am unsure where I should direct this question, if not here.

Could you please provide the version of mpfr the macOS binary is compiled against?  (Also the version of the gmp might be helpful.)

----

I have installed ViennaRNA 2.4.16 (latest) compiled for macOS using the DiskImage; thank you.

RNAfold (and others presumably) are compiled against `libmpfr.4.dylib`. Which version of mpfr provides that version of the shared library?  (I'll guess it is 4.0.2, as mpfr moves slowly and that was most recent before 4.1.0.)

I have mpfr 4.1.0 installed (via homebrew), but it provides `libmpfr.6.dylib`.  I can probably change mpfr with less effort than compiling ViennaRNA, so I would take that approach.

As a workaround, I changed the binary and `RNAfold` seems to run fine:

`install_name_tool -change /usr/local/opt/mpfr/lib/libmpfr.4.dylib /usr/local/opt/mpfr/lib/libmpfr.6.dylib /usr/local/bin/RNAfold`

**Comment by RaumZeit** [comment]
Sorry for getting back on this issue so late. The thing is that we never bothered looking into which version of `mpfr` the binary packages were linked against. I've just been looking into this issue the other day and found that on my build machine an older `mpfr` was installed via `homebrew`. I've updated the package in the meantime, though the installer still links against this old version.
For future releases, I think, the best would be to provide two installers, one that doesn't link against `mpfr` at all, since it requires the users to have the respective package installed via `homebrew`, and another one that does link against that and other `homebrew` libraries. Maybe this will alleviate the problem of missing libraries.

**Comment by RaumZeit** [comment]
This should be all fixed with the new version 2.4.18. We now provide two  pre-build binary installer packages, one that links against latest libraries in homebrew at the time of building the installer, and a second, that doesn't link at all against any package from homebew.

I'm closing this issue now, feel free to re-open if required.
